export const SHARED_LOGIN = 'SHARED_LOGIN';
export const SHARED_LOGIN_SUCCESS = 'SHARED_LOGIN_SUCCESS';
export const SHARED_LOGIN_ERROR = 'SHARED_LOGIN_ERROR';
export const SHARED_LOGOUT = 'SHARED_LOGOUT';
export const SHARED_LOGOUT_SUCCESS = 'SHARED_LOGOUT_SUCCESS';
export const SHARED_LOGOUT_ERROR = 'SHARED_LOGOUT_ERROR';
